#pragma kernel CSMain

Texture2D<float4> InputTexture;
RWTexture2D<float4> OutputTexture;

int _Width;
int _Height;
int _BorderSize;

[numthreads(8, 8, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{
    if (id.x >= _Width || id.y >= _Height)
        return;

    int2 uv = int2(id.x, id.y);

    float4 color = InputTexture[uv];
    float sdf = color.r;

    float maxResolution = (float)max(_Width, _Height);
    float borderThreshold = (float)_BorderSize / maxResolution;

    float border = step(0.0001, sdf) * step(sdf, borderThreshold);

    OutputTexture[uv] = float4(border, border, border, 1.0);
}
